version: '3.4' 

services:
  dbPG:
    image: postgres    
    restart: always   
    environment: 
      POSTGRES_USER: aspnetrestudemy       
      POSTGRES_PASSWORD: docker!123
      POSTGRES_DB: rest_with_asp_net_udemy
    ports:
      - 5432:5432
    networks:
      - udemy-network 
  adminer:
    image: adminer
    restart: always
    ports:
      - 3320:3326
  db:
    image: rest-with-asp-net-udemy-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: aspnetrestudemy
      MYSQL_USER: aspnetrestudemy
      MYSQL_PASSWORD: docker!123
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3310:3306
    networks:
      - udemy-network
      
  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge