version: '3.4' 

services:   
  adminer:
    image: adminer
    restart: always
    ports:
      - 3320:3326
  dbMSQL:
    image: mcr.microsoft.com/mssql/server:2017-latest    
    restart: always   
    container_name: restSQLServer
    environment: 
      TZ: America/Sao_Paulo
      ACCEPT_EULA:  "Y"       
      SA_PASSWORD: docker!123 
    ports:
      - 1433:1433
    networks:
      - udemynetwork
  db:
    image: rest-with-asp-net-udemy-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: aspnetrestudemy
      MYSQL_USER: aspnetrestudemy
      MYSQL_PASSWORD: docker!123
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3310:3306
    networks:
      - udemynetwork      
  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    links:
    - db
    - dbMSQL
    depends_on:
    - db 
    - dbMSQL 
    networks:
    - udemynetwork
networks:
  udemynetwork:
    driver: bridge